# Generated by Django 5.0.6 on 2024-05-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_csv_files_files_model_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files_model',
        ),
    ]
